### ISSUE TITLE
CRUD for website

### ISSUE THREAD

**Issue by PhyllisWong** [Check-Pleaze/check-pleaze-api#8]
For updating content to the web

**Comment by joerez** [comment]
Just to be clear, what you're asking for is a way to serve content to the frontend landing page, from the backend? 

This means there should also be some sort of authentication whereby an admin can log in, to edit and change the content via form.

If this is the case, should we use markdown sanitization on the content input?

**Comment by PhyllisWong** [comment]
The landing page is not going to have content served from the database. The landing page should be static.
